# example netlify.toml
[build]
  command = "vite build"
  functions = "netlify/functions"
  publish = "../www"

  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

  [[redirects]]
    from = "/api/*"
    to = "https://smartpro.solutions/api"
    status = 200